<?php
/**
 * REST callback functions of the plugin.
 *
 * @link       
 * @since      2.6.7.3
 *
 * @package    Applyonline
 * @subpackage Applyonline/rest
 */

/**
 * The updater functionality of the plugin.
 *
 * Defines the plugin name, version
 *
 * @package    Applyonline
 * @subpackage Applyonline/rest
 * @author     Farhan Noor <profiles.wordpress.org/farhannoor>
 */
class Applyonline_Rest_Functions{
    
    var $uploads;
    
    function __construct() {
        add_filter( 'aol_form_errors', [$this, 'file_uploader'], 10,3 );
    }
    
        function upload_path($uploads){
                $subdir = apply_filters('aol_upload_folder', 'applyonline');
                //$default = wp_upload_dir(); $default['basedir'];
                $aol_upload_path = get_option('aol_upload_path');
                $uploads['path'] = wp_normalize_path($uploads['basedir'] . '/' . $subdir);
                $uploads['subdir'] = wp_normalize_path( '/' . $subdir);
                $uploads['url'] = $uploads['baseurl']. '/' . $subdir;

                if(!empty($aol_upload_path)){
                    $uploads['basedir'] = $aol_upload_path;
                    $uploads['path'] = wp_normalize_path($aol_upload_path . '/' . $subdir);
                }
                return $uploads;
        }

        function file_uploader($errors, $post, $files){
            if(empty($files)) return $errors; //If no files are being uploaded, just quit.

            $upload_overrides = array( 'test_form' => false );

            /*Initialixing Variables*/
            //$errors = new WP_Error();

            $uploads = array();
            $user = get_userdata(get_current_user_id());

            if ( ! function_exists( 'wp_handle_upload' ) ) {
                require_once( ABSPATH . 'wp-admin/includes/file.php' );
            }
            
            foreach($files as $key => $val):
                if(empty($val['name'])) continue;

                $field = get_post_meta($post['ad_id'], $key, TRUE);
                
                if( isset($field['allowed_file_types']) AND !empty($field['allowed_file_types']) ){
                    $allowed_types = str_replace(' ', '',  $field['allowed_file_types']);
                } else{
                    $allowed_types = str_replace(' ', '', get_option('aol_allowed_file_types'));
                }
                
                //Check if single File Type or multiple, if multiple convert it to an array.
                $allowed_types = strstr($allowed_types, ',') == FALSE ? array($allowed_types) : explode(',', $allowed_types );
                
                $upload_size = empty($field['allowed_size']) ? get_option_fixed('aol_upload_max_size', 1) : $field['allowed_size'];
                $max_upload_size = $upload_size*1048576; //Multiply by KBs
                
                if($max_upload_size < $val['size']){
                        $errors->add('max_size', sprintf(esc_html__( '%s is oversized. Must be under %s MB', 'apply-online' ), $val['name'] , $upload_size));
                }

                /* Check File Size */
                $file_type_match = 0;
                $filetype = wp_check_filetype(  $val['name'] );
                $file_ext = strtolower($filetype['ext']);
                if( !in_array($file_ext, $allowed_types) ) $errors->add('file_type', sprintf(esc_html__( 'Invalid file %1$s. Allowed file types are: %2$s', 'apply-online' ), $val['name'], implode (',', $allowed_types)));
                $errors = apply_filters('aol_before_file_upload_errors', $errors);
                if(empty($errors->errors)){
                    do_action('aol_before_file_upload', $key, $val, $post);
                                        
                    add_filter('upload_dir', array($this, 'upload_path')); //Change upload path.
                    $movefile = wp_handle_upload( $val, $upload_overrides );
                    if ( $movefile && ! isset( $movefile['error'] ) ) {
                        $uploads[$key] = $movefile;
                        $uploads[$key]['name'] = $val['name'];
                        //update_user_meta(get_current_user_id(), $key, $movefile['url'] );
                    } else {
                        /**
                         * Error generated by _wp_handle_upload()
                         * @see _wp_handle_upload() in wp-admin/includes/file.php
                         */
                         $errors->add('file_move', $val['name'].': '.$movefile['error']);
                    }
                }
            endforeach;
            //return array('errors' => $errors, 'uploads' => $uploads);
            $this->uploads = $uploads;
            return $errors;
        }
                        
        /**
         * The function processes and saves application form info in the database. 
         */
        public function form_post( WP_REST_REQUEST $request ){
            $form_data = $request->get_params();

            //Get ad id from the form data.
            $ad_id = $form_data['ad_id'];

            do_action( 'aol_before_app_process', $form_data );
            
            $app_field = $app_data = array();
            /*Initializing Variables*/
            $errors = new WP_Error();
            
            //@todo: Save transcript in json/serialized format as one postmeta field instead of seperate field for each form field for ad.

            //$transcript: the original form fields of the ad.
            $transcript = $ad_transcript = get_post_meta($ad_id, '', TRUE);

            //If no fields found.
            if( empty($transcript) ){
                return new WP_REST_Response( ['message' => "Are you nuts?"], 404 );
            }

            //Rule out expired ads.
            $expiry_date = $transcript['_aol_ad_closing_date'][0];
            if( !empty($expiry_date) AND (int)$expiry_date < time() ){
                return new WP_REST_Response( ['message' => esc_html__('The submission deadline for this ad has passed. Please contact support for more details.', 'apply-online')], 404 );
            }
            
            //Remove unnecessary array elements from the parent ad array.
            foreach($transcript as $key => $val):
                if( substr($key, 0, 9) != '_aol_app_' ){
                    unset($transcript[$key]);
                } else{
                    $key = sanitize_key($key);
                    $transcript[$key] =  maybe_unserialize( $val[0] );
                }
            endforeach;
            
            //var_dump($transcript); die();
            $transcript = apply_filters('aol_form_for_app_validation', $transcript, $form_data, $_FILES);
            
            //Start - Check for required fields.
            //Loop through each form field & check received application data.
            foreach( $transcript as $key => $val ):

                //Excludes non form fields from check.
                if( in_array($val['type'], ['separator', 'seprator', 'paragraph']) ) continue;

                //Check existence. All fields in transcript must be present in the application form.
                if( !isset($form_data[$key]) ) $errors->add('required', esc_html__('Some fields are missing.', 'apply-online') );

                //Check for required fields.
                if( isset($val['required']) AND (int)$val['required'] == 1 ){
                    //Check file fields.
                    if( $val['type'] == 'file' AND empty($_FILES[$key]['name']) ){
                        $errors->add('required', sprintf( esc_html__('%s field is required.', 'apply-online'), $val['label']) );
                    }

                    //Check all other fields.
                    elseif( empty($form_data[$key]) ){
                        $errors->add('required', sprintf(esc_html__('%s field is required.', 'apply-online'), '"'.$val['label'].'"') );                        
                    }
                }

                //eMail validation.
                if( $val['type'] == 'email'){
                    if( !empty($form_data[$key]) and !is_email($form_data[$key]) ) $errors->add('email', sprintf(esc_html__('%s is invalid.', 'apply-online'), '"'.$val['label'].'"'));
                }
            endforeach;

            //You can hook 3rd party form errors here.
            $errors = apply_filters('aol_form_errors', $errors, $form_data, $_FILES);

            $error_messages = $errors->get_error_messages();
            //$error_messages = array_merge($error_messages, $upload_error_messages);

            if( !empty( $error_messages ) ){
                $error_html = '<ul><li>';
                $error_html .= implode('</li><li>', $error_messages);
                $error_html .= '</li></ul>';
                $response = array( 'message' => $error_html );    //generate the error response.

                return new WP_REST_Response($response, 400);
            }
            //End - Check for required fields

            //Deprictated since 2.2.2. Will be deleted soon. Use aol_app_final_fields hook instead
            $app_data = apply_filters('aol_app_fields_to_process', $app_data, $form_data);
            $parent_id = $app_data['ad_id'] = $ad_id;            

            $applicant_emails = array();
            foreach($transcript as $key => $val){

                $form_data[$key] = is_array( $form_data[$key] ) ? array_map( 'sanitize_text_field', $form_data[$key] ) : sanitize_textarea_field( $form_data[$key] );

                //Support for previous versions.
                if( !isset($val['label']) ) $val['label'] = str_replace('_',' ', substr($key, 9));

                if( !isset($form_data[$key]) ) continue;
                $app_field = maybe_unserialize($val);

                //normalizing path & sanitizing data before input.
                $val = is_array($form_data[$key]) ? array_map('sanitize_text_field', $form_data[$key]) : sanitize_textarea_field($form_data[$key]);
                $key = sanitize_key($key);

                //Populating array with sanitized keys & values.
                $app_data[$key] = $val;

                /*get applicant's email for email notification*/
                if( $app_field['type'] == 'email' AND isset($app_field['notify']) AND $app_field['notify']==1 ){
                    $applicant_emails[] = $val;
                }
            }

            if(isset($this->uploads)){
                foreach($this->uploads as $name => $file){
                    //FILTER_SANITIZE_URL convert french file names to enlgish file names. 
                    $args = array('file'=> array('filter' => FILTER_SANITIZE_STRING, 'flags'), 'url' => FILTER_SANITIZE_STRING, 'type' => FILTER_SANITIZE_STRING, 'name' => FILTER_SANITIZE_STRING);
                    $app_data[sanitize_key($name)] = filter_var_array($file, $args);
                }
            }

            $app_data = apply_filters('aol_app_final_fields', $app_data, $form_data);

            $args =  array(
                'post_type'     => 'aol_application',
                'post_parent'   => $parent_id,
                'post_title'    => get_the_title($parent_id),
                'post_status'   => 'pending',
                //'tax_input'     => array('aol_application_status' => 'pending'), Depricated since 2.6.7.4
            );
            do_action('aol_before_app_save', $app_data, $form_data); //Depricated Since 2.5
            do_action('aol_before_save_app', $app_data, $form_data);

            $args = apply_filters('aol_insert_app_data', $args, $app_data);

            $args['ID'] = $pid = wp_insert_post($args, TRUE);

            //If post is not saved and generates an error, return error message to the client and terminate further execution.
            if( is_wp_error($pid) ){
                $response = array( 'code' => $pid->get_error_code(), 'reason' => 'Something went wrong.', 'message' => $pid->get_error_message() ); // generate the error response.
                //$this->response($response, 400);
                return new WP_REST_Response($response, 500);
            }

            foreach($app_data as $key => $val):
                update_post_meta($pid, $key, $val);
                $args['meta_input'][$key] = $val;
            endforeach;

            $parent = get_post($parent_id);
            update_post_meta($pid, 'aol_ad_id', $parent->ID);
            update_post_meta($pid, 'aol_ad_author', $parent->post_author);

            /* Saving Ad Transcript Since v2.2 */
            foreach($ad_transcript as $key => $val){
                if( substr($key, 0, 9) == '_aol_app_' OR $key == '_aol_fields_order' ) $ad_transcript[$key] = $val[0];
                else  unset($ad_transcript[$key]);
            }
            update_post_meta($pid, 'ad_transcript', $ad_transcript );
            /* End Saving Ad Transcript Since v2.2 */

            //wp_set_post_terms( $pid, 'pending', 'aol_application_status' ); Depreicated since 2.6.7.4

            do_action('aol_after_app_save', $pid, $app_data); //Depricated since 2.5
            do_action('aol_after_save_app', $pid, $app_data);
            //do_action('aol_after_app_save', $pid, $form_data);

            //Email notification Since v2.2 
            if( $args['post_status'] != 'draft'){
                $this->applicant_email_notification( $pid, $args, $applicant_emails );

                $recipients = sanitize_textarea_field( get_post_meta($parent_id, '_recipients_emails', true) );
                if( !empty($recipients) ) $recipients = explode("\n", str_replace(array("\r", " "),"", $recipients));
                $this->admin_email_notification($recipients, $pid, $args, $this->uploads, $parent->post_author);                    
            }

            $divert_page = get_option('aol_thankyou_page');

            empty($divert_page) ? $divert_link = null :  $divert_link = get_page_link($divert_page);
            $message = str_replace('[id]', $pid, get_option_fixed('aol_application_success_alert', esc_html__('Form has been submitted successfully with application id [id]. If required, we will get back to you soon!', 'apply-online')) );
            // generate the response alert.
            $response = apply_filters( 
                'aol_application_success_response', 
                array( 'divert' => $divert_link, 'hide_form'=>TRUE , 'message'=>$message ),
                $app_data
            );
            //$this->response($response);
            return new WP_REST_Response( $response );
        }

        /**
         * Application success Email notification for Applicants
         * 
         * @param type $post_id
         * @param type $post
         * @param type $uploads
         * @return boolean
         */
        function applicant_email_notification($post_id, $post, $emails){
            if(empty($emails)) return;
            $post = (object)$post;

            $subject = str_replace('[title]', $post->post_title, get_option('aol_success_mail_subject', 'Your application for [title]') );

            $headers = aol_from_mail_header();
            $attachments = array();

            //@todo need a filter hook to modify content of this email message and to add a from field in the message.
            $message="<p>Hi there,</p>"
                ."<p>Thank you for showing your interest in the ad: [title]. Your application with id [id] has been received. We will review your application and contact you if required.</p>"
                .sprintf(esc_html__('Team %s'), get_bloginfo('name'))."<br/>"
                .site_url()."<br/>"
                ."Please do not reply to this system generated message.";

            $message = str_replace( array('[title]', '[id]'), array($post->post_title, $post->ID), get_option('aol_success_mail_message', $message) );
            $aol_email = apply_filters(
                        'aol_applicant_mail_notification', 
                        array('to' => $emails, 'subject' => $subject, 'message' => nl2br($message), 'headers' => $headers), 
                        $post_id,
                        $post
                    );

            do_action('aol_email_before', array('to' => $emails, 'subject' => $subject, 'message' => nl2br($message), 'headers' => $headers), $post_id, $post);

            wp_mail( $aol_email['to'], $aol_email['subject'], $aol_email['message'], $aol_email['headers']);

            do_action('aol_email_after', $emails, $subject, nl2br($message), $headers);

            return true;
        }

        function admin_email_notification($emails, $post_id, $post, $uploads, $post_author ){
            $post = (object)$post;

            //send email alert.
            $post_url = admin_url("post.php?post=$post_id&action=edit");

            if( empty($emails) ){                
                //Get global recipients
                $emails_string = sanitize_textarea_field( get_option_fixed('aol_recipients_emails', get_option('admin_email')) );
                
                $emails = explode("\n", str_replace(array("\r", " "),"", $emails_string) );
            }

            $emails = array_map('sanitize_email', $emails);
            
            $author_notification = get_option('aol_ad_author_notification');
            if( $author_notification ){
                $author = get_userdata( $post_author );
                if( !in_array($author->user_email, $emails) ) array_push($emails, $author->user_email);
            }
            /*
            // Get the site domain and get rid of www.
            $sitename = strtolower( $_SERVER['SERVER_NAME'] );
            if ( substr( $sitename, 0, 4 ) == 'www.' ) {
                $sitename = substr( $sitename, 4 );
            }
            $from_email = 'do-not-reply@' . $sitename;
            $headers = array('Content-Type: text/html', "From: ". wp_specialchars_decode(get_bloginfo('name'))." <$from_email>");
             * 
             */

            //$subject = sprintf(esc_html__('New application for %s', 'apply-online'), sanitize_text_field($post->post_title));
            $subject = str_replace( array('[id]' ,'[title]'), array($post->ID ,$post->post_title), get_option('aol_admin_mail_subject', 'New application [id] for [title]') );
            $headers = aol_from_mail_header();

            //@todo need a filter hook to modify content of this email message and to add a from field in the message.
            $message=   '<p>'.esc_html__('Hi,', 'apply-online').'</p>'
                        .'<p>'
                        .sprintf(esc_html__('A new application for the ad %1$s received on %2$s website.', 'apply-online'), '<b>'.$post->post_title.'</b>', '<b>'.get_bloginfo('name').'</b>')
                        .'</p><p>'
                        .sprintf(esc_html__('%sClick Here%s to access this application.', 'apply-online'),'<b><a href="'.$post_url.'">', '</a></b>')
                        .'</p>'
                        .esc_html__('Thank you', 'apply-online')
                        .'<br /><p>----<br />'
                        .sprintf(esc_html__('This is an automated response from Apply Online plugin on %s', 'apply-online'), '<a href="'.site_url().'" >'.get_bloginfo('name').'</a>')
                        .'</p>';

            $message = apply_filters('aol_email_notification', $message, $post_id); //Deprecated.
            $aol_email = apply_filters(
                        'aol_email', 
                        array( 'to' => $emails, 'subject' => $subject, 'message' => $message, 'headers' => $headers, 'attachments' => array() ), 
                        $post_id,
                        $post,
                        $uploads
                    );

            do_action('aol_email_before', array('to' => $emails, 'subject' => $subject, 'message' => nl2br($message), 'headers' => $headers), $post_id, $post, $uploads);

            wp_mail( $aol_email['to'], $aol_email['subject'], $aol_email['message'], $aol_email['headers'], $aol_email['attachments']);
                        
            do_action('aol_email_after', $emails, $subject, nl2br($message), $headers);

            return true;
        }
        
        /**
         * This function returns REST or AJAX response back to the client and terminate further execution of the calling function.
         * 
         * @param array $result The actual data that is being returned to the client. It is the body of the HTTP response, containing the information that needs to be received from the server
         * @param int $code HTTP response status code. Default is 200 successful. If $result variable is empty, it will return 404 not found status code.
         * @param string $header HTTP header to be sent to the requesting client.
         * 
         * @return NULL NONE This function terminates further execution hence it retunrs nothing.
         */
        function response( $result = [], $code = 200, $header = "Content-type:application/json" ){
            if( empty($result) ) $code = 404;
            
            http_response_code($code);
            header($header);
            exit( json_encode($result) );

            //@todo: Proposed response.
            $response = new WP_REST_Response();
            $response->set_status($code);
            $response->set_data($result);
            return $response;
        }
}